#Tomcat Server
server:
  port: 8090

spring:
  thymeleaf:
    prefix: classpath:views/
    suffix: .html
    mode: HTML5
    cache: false
    check-template-location: true
       
  devtools: 
   livereload:  
    enabled: true
    
  #JDBC 설정
  datasource:
    url: jdbc:mysql://localhost:3307/mango?autoReconnect=true
    username: root
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: C:/home/mango #윈도우에서 테스트할 때는 정확한 드라이브 값까지 줘야 함.
      #location: /home/mango 리눅스 서버에 저장하고 싶은 경로로 변경하면 됩니다.
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 890619526612-hmagm7jt9l7q4fct97b7u0bjrrnkuhoc.apps.googleusercontent.com
            client-secret: qLicjAizb4NSwZ34XFEt8_Vx
          
          facebook:
            client-id: 430401751577188
            client-secret: e54aadb50ce5d9e33289712a7b7cb1c3
custom: 
  oauth2: 
    kakao: 
      client-id: 99143cb46e73d1fe659fbf01cd9ac252
      client-secret: BxrrLCXMPFlZQ4230bOChLMpNsYhSJn4
    naver: 
      client-id: y2q7zvHFZQ7eejC9xoM0
      client-secret: mahnIRdkX4
      
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.mango.model
